# Fly.toml file generated for your app
# Documentation: https://fly.io/docs/reference/configuration

app = "xoxogossipproject"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[[deploy.targets]]
  name = "production"
  regions = ["region1", "region2", "france"]

